### ISSUE TITLE
not pulling any of my devices

### ISSUE THREAD

**Issue by vikramhn** [reincubate/ricloud-csharp#1]
i used the defaut api username and key with my icloud account. login is succesful but mClient.Devices.Length is zero

**Comment by adriangonz** [comment]
@vikramhn does any of your devices have a recent backup on iCloud?

**Comment by vikramhn** [comment]
No, I dont have a backup. I was looking to check if you have findmydevice api similar to https://github.com/matt-kruse/find-my-iphone. May be your api works based on  backup data only and not realtime information?

[https://avatars2.githubusercontent.com/u/2974436?v=3&s=400]https://github.com/matt-kruse/find-my-iphone

GitHub - matt-kruse/find-my-iphone: A Node module to ...https://github.com/matt-kruse/find-my-iphone
github.com
find-my-iphone - A Node module to trigger the "Find My iPhone" feature from iCloud, to play a sound on the phone

**Comment by afit** [comment]
Hi Vikram, sorry for not coming back earlier. We've got a fix on our trial cluster coming out shortly which will make this work for you. Yes, we do support the use case you describe. You'll get a reply from our support team shortly! :-)

**Comment by vikramhn** [comment]
Thanks Aidan.  I just tried and mClient.Devices was still 0 count.  Let me know when the cluster is updated.

**Comment by acyrl** [comment]
Dear Vikram,

We have updated the icloud API so that it has two new features:
1. You can pass an empty device - that is, the empty string '' - when requesting the location data. This will return the location of every device whether it has a backup or not.
2. We have added a new data type that allows you to list all devices associated with an iCloud account. The bitmask value for this data type is 167777216.

it’s not available on the default trial key, though, so you’ll need to arrange a full trial with the team on enterprise@reincubate.com.

Kind regards,

Acyr
